export const supportersArray = [
  {
    title: 'Save the Children',
    url: 'https://www.savethechildren.net/what-we-do/emergencies/ukraine-crisis',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1@2x.png',
    imgRetinaThree: './images/fond-1@3x.png'
  },
  {
    title: 'Project HOPE',
    url: 'https://www.projecthope.org/country/ukraine/',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'International Medical Corps',
    url: 'https://internationalmedicalcorps.org/country/ukraine/',
    img: './images/fond-1.png',
    imgRetinaTwo: "./images/fond-1.png",
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'Medicins Sans Frontieres',
    url: 'https://www.msf.org/ukraine',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'RAZOM',
    url: 'https://www.razomforukraine.org/',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'Action against hunger',
    url: 'https://www.actionagainsthunger.org/location/europe/ukraine/',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: "./images/fond-1.png",
  },
  {
    title: 'World vision',
    url: 'https://www.wvi.org/emergencies/ukraine',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'Serhiy Prytula Charity Foundation',
    url: 'https://prytulafoundation.org/en',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
  {
    title: 'UNITED24',
    url: 'https://u24.gov.ua/uk',
    img: './images/fond-1.png',
    imgRetinaTwo: './images/fond-1.png',
    imgRetinaThree: './images/fond-1.png',
  },
];
